### PR TITLE
Clean/remove dbd base path

### PR DESCRIPTION
**Pull request by ploki**
removed base path from dbd_url configuration

### CODE REVIEW

**Comment by ploki** [comment]
wrong repo

**Comment by ffilz** [comment]
Hmm, this looks possibly interesting to the wider community. I recommend becoming more visible to the community.

**Comment by ploki** [comment]
I agree. It is still in the early phase of development. And prior to making it more visible, I have to tackle with the big cache_inode rip out (cafbe60c47c4ed4ac4abe8f78083d88f4e5bbbec) since I started development against V2.4-dev-15.

**Comment by ffilz** [comment]
Sorry about that :-) One reason to be visible to the community is less surprise when big stuff happens...

**Pull request closed without merging**
