### PR TITLE
layoutget: fix escape on error condition

### PR DESCRIPTION
**Pull request by kofemann**
The current code is broken.  Either you escape on error, do not check the condition at all ( and document why).

### CODE REVIEW

**Comment by ffilz** [comment]
Is this issue fixed in the V2.2 development chain?

 

Any bugfix needs to go into the current development chain before being backported to stable branches.

 

Thanks

 

Frank

**Comment by kofemann** [comment]
Looks like it exists in all branches (so called day-0).

**Comment by ffilz** [comment]
Could you push a branch rebased to V2.2-dev-22 (or 23 if you are unable to push before I get V2.2-dev-23 pushed)?

 

Then once the fix is in V2.2-dev, we can get a fix into V2.1 stable branch.

 

Marc, could you review this fix also?

 

Thanks

 

Frank

**Comment by kofemann** [comment]
The commit https://github.com/nfs-ganesha/nfs-ganesha/commit/34d7e5c409806e077341410d82cf5ec89ad6f3ae have fixed it in dev branch. I was confused by the fact that master points to 2.1 branch

**Comment by ffilz** [comment]
Oh, good.

 

This may heap into the pile of stuff that says that the best fix for 2.1 is move to 2.2 ASAP…

 

Frank

**Comment by soumyakoduri** [comment]
Looks like https://github.com/nfs-ganesha/nfs-ganesha/commit/34d7e5c409806e077341410d82cf5ec89ad6f3ae patch can be safely merged to V2.1-stable branch as well. Please confirm. I shall then push it to that branch.

**Pull request closed without merging**
