### PR TITLE
vfs: Add pNFS support and MDCACHE.

### PR DESCRIPTION
**Pull request by olifre**
Hi, 

this PR is just to get some feedback, whether I am on track - and how to test things... 

As shortly discussed on IRC, I looked into the old FSAL_LUSTRE code and extracted the bits (hopefully all) necessary for MDS / DS => pNFS support. 
As noted there, this is meant to support the case of a mounted shared filesystem (e.g. Lustre, BeeGFS) on several data servers to increase bandwidth via pNFS. 

I got things to compile by adapting to some renamings of struct members in the codebase, in once case rewriting something Lustre-specific to use vfs_open instead, and finally, of course, by sed'ing Lustre to VFS ;-). 

I did not yet do any functional test - is there a test suite available in some way, or do you have some test setup for development? 
Could somebody have a look and tell me whether something is blatantly wrong?

### CODE REVIEW

**Comment by ffilz** [comment]
Note that we do code review/submission via gerrithub (see src/CONTRIBUTING_HOWTO.txt).

**Comment by olifre** [comment]
Understood! should we close this then, and I open it freshly on gerrit?

**Comment by olifre** [comment]
Since I also see the pre-commit linting right now, that would also mean I fix some basics first, like indentation and stuff.

**Comment by olifre** [comment]
Here you go:
https://review.gerrithub.io/374370
There are still (from the "formal" point of view) the file headers to fix, but it's probably better to get the functional part working / checked first.

**Comment by martinetd** [comment]
Closing because it's been taken to gerrithub

**Pull request closed without merging**
