### PR TITLE
Update ganesha_mgr_utils.py

### PR DESCRIPTION
**Pull request by deepanshuwadhwa7**
ganesha_mgr show exports
ganesha_mg show clients
both commands are failing with "IndexError: tuple index out of range" as the dbus struct has changed.

This change handles change done to dbus struct

### CODE REVIEW

**Comment by deepanshuwadhwa7** [comment]
Issue -

[root@nsds1 /]# ganesha_mgr help | grep -A5 show
   show :
      clients: Displays the current clients
      version: Displays ganesha release information
      posix_fs: Displays the mounted POSIX filesystems
      exports: Displays all current exports
      idmap: Displays the idmapper cache
[root@nsds1 /]# ganesha_mgr show clients
Show clients
Traceback (most recent call last):
  File "/usr/bin/ganesha_mgr", line 466, in <module>
    clientmgr.showclients()
  File "/usr/bin/ganesha_mgr", line 56, in showclients
    status, errormsg, reply = self.clientmgr.ShowClients()
  File "/usr/lib/python3.6/site-packages/Ganesha/ganesha_mgr_utils.py", line 94, in ShowClients
    lasttime = cl_[9]
IndexError: tuple index out of range
[root@nsds1 /]# ganesha_mgr show exports
Show exports
Traceback (most recent call last):
  File "/usr/bin/ganesha_mgr", line 470, in <module>
    exportmgr.showexports()
  File "/usr/bin/ganesha_mgr", line 92, in showexports
    status, msg, reply = self.exportmgr.ShowExports()
  File "/usr/lib/python3.6/site-packages/Ganesha/ganesha_mgr_utils.py", line 223, in ShowExports
    lasttime = ex[10]
IndexError: tuple index out of range



Post Fix -

[root@nsds1 /]# ganesha_mgr show clients
Show clients
Timestamp:  Wed Sep  7 01:39:18 2022 508664294  nsecs
Clients:
 IP addr,  nfsv3, mnt, nlm4, rquota,nfsv40, nfsv41, nfsv42, 9p, last
 ::ffff:172.16.5.87,  1,  0,  0,  0,  1,  0,  0,  0, Wed Sep  7 01:39:13 2022 165382019 nsecs
 ::ffff:172.16.5.115,  1,  0,  0,  0,  1,  0,  0,  0, Wed Sep  7 00:50:46 2022 666135400 nsecs
[root@nsds1 /]# ganesha_mgr show exports
Show exports
Timestamp:  Mon Sep  5 19:45:23 2022 334251764  nsecs
Exports:
  Id, path,    nfsv3, mnt, nlm4, rquota,nfsv40, nfsv41, nfsv42, 9p, last
 1,  /mnt/lustre/mac9495/nfs,  1,  0,  0,  0,  1,  0,  0,  0, Wed Sep  7 00:50:46 2022, 666135400 nsecs
 0,  /,  0,  0,  0,  0,  0,  0,  0,  0, Thu Jan  1 00:00:00 1970, 0 nsecs

**Comment by deepanshuwadhwa7** [comment]
Ganesha version ->

[root@nsds1 /]# ganesha_mgr show version
NFS-Ganesha Release = V4.0.4
ganesha compiled on Sep  1 2022 at 06:32:16
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = e7e89686f284a29a040f1376155b3415a5dccc20
Git Describe =

**Comment by ffilz** [comment]
Please submit this via Gerrithub as per src/CONTRIBUTING_HOWTO.txt

**Comment by ffilz** [comment]
Is there still interest in this patch? If so, please submit via gerrithub.

**Comment by deepanshuwadhwa7** [comment]
Sure, I will submit it over the weekend.

Sorry for the delay.


________________________________

**Comment by ffilz** [comment]
I hope to tag Ganesha V4.1 this week. If you still wish this patch to go in, it should be submitted to Gerrithub for review ASAP.

**Comment by skmprabhu** [comment]
submitted patch in https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/546426

**Comment by deepanshuwadhwa7** [comment]
Thanks Prabhu.

-Deepanshu
________________________________

**Comment by ffilz** [comment]
Patch has been merged, closing.

**Pull request closed without merging**
